version: '2'
services:
  database:
    build: db
    restart: always
    environment:
      POSTGRES_DB: lab3
      POSTGRES_PASSWORD: postgres
  app:
    build: app
    depends_on: [database]
    links:
      - database
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:postgres@localhost:5432/lab3'
